---
- name: Pull MariaDB container image
  docker_image:
    name: "{{ mariadb_docker_imagename }}"
    tag: "{{ mariadb_docker_imagetag }}"
    state: present
  delegate_to: "{{ item.public_dns_name }}"
  remote_user: ec2-user
  become: true
  with_items: "{{ ec2.instances }}"

- name: Run MariaDB container
  docker_container:
    name: "{{ mariadb_docker_containername }}"
    image: "{{ mariadb_docker_imagename }}"
    exposed_ports: 3306
    detach: yes
    restart_policy: unless-stopped
    env: 
      MYSQL_ROOT_PASSWORD: "{{ mariadb_root_password }}"
      MYSQL_USER: "{{ mariadb_user }}"
      MYSQL_PASSWORD: "{{ mariadb_password }}"
    state: started
  delegate_to: "{{ item.public_dns_name }}"
  remote_user: ec2-user
  become: true
  with_items: "{{ ec2.instances }}"
